kind: pipeline
type: docker
name: default

clone:
  disable: true

steps:
  - name: Create token
    image: mcr.microsoft.com/powershell:latest
    environment:
      TENANTID:
        from_secret: TENANTID
      CLIENTID:
        from_secret: CLIENTID
      CLIENTSCT:
        from_secret: CLIENTSCT
    commands: 
      - pwsh /drone/src/IPM_token.ps1 $TENANTID $CLIENTID $CLIENTSCT

  - name: read
    pull: if-not-exists
    image: alpine
    commands:
      - echo $LANG
      - source .env
      - echo $LANG