kind: pipeline
name: default

clone:
  disable: true

steps:
  - name: Create token
    image: mcr.microsoft.com/powershell:latest
    environment:
      TENANTID:
        from_secret: TENANTID
      CLIENTID:
        from_secret: CLIENTID
      CLIENTSCT:
        from_secret: CLIENTSCT
    commands: 
      - pwsh -Command {$resourceAppIdURI = 'https://database.windows.net/'
        $tokenResponse = Invoke-RestMethod -Method Post -UseBasicParsing -Uri "https://login.windows.net/$($TENANTID)/oauth2/token" -Body @{resource=$resourceAppIdURI 
        client_id=$CLIENTID 
        grant_type='client_credentials' 
        client_secret=$CLIENTSCT} -ContentType 'application/x-www-form-urlencoded'
        if ($tokenResponse) {
        Write-debug “Access token type is $($tokenResponse.token_type), expires $($tokenResponse.expires_on)”
        $Token = $tokenResponse.access_token
        }}

  - name: read
    pull: if-not-exists
    image: alpine
    commands:
    - echo $LANG
    - source .env
    - echo $LANG